// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYAd1XC7Z-UTuebbL9jVV9bWeih0K8ZDU',
    appId: '1:171211831622:web:398eb4affdc25987b50d47',
    messagingSenderId: '171211831622',
    projectId: 'social-app-d7c06',
    authDomain: 'social-app-d7c06.firebaseapp.com',
    storageBucket: 'social-app-d7c06.appspot.com',
    measurementId: 'G-2HG3VNZJYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3geXHVdxybM751ci7CPPFEaE7jUx3bg',
    appId: '1:171211831622:android:7ccdc2fd3db2d26eb50d47',
    messagingSenderId: '171211831622',
    projectId: 'social-app-d7c06',
    storageBucket: 'social-app-d7c06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP2uQpkADwTEV9qgjtctlvphgLaYU1zHw',
    appId: '1:171211831622:ios:84a1b70bbdc7f706b50d47',
    messagingSenderId: '171211831622',
    projectId: 'social-app-d7c06',
    storageBucket: 'social-app-d7c06.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP2uQpkADwTEV9qgjtctlvphgLaYU1zHw',
    appId: '1:171211831622:ios:66c923087faf847bb50d47',
    messagingSenderId: '171211831622',
    projectId: 'social-app-d7c06',
    storageBucket: 'social-app-d7c06.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
